RoleTopMVC/ViewModels/DashboardViewModel.cs
using System.Collections.Generic;
using RoleTopMVC.Models;

namespace RoleTopMVC.ViewModels
{
    public class DashboardViewModel : BaseViewModel
    {
        public List<Agendamento> Agendamento {get; set;}
        public uint EventosAprovados {get; set;}
        public uint EventosReprovados {get; set;}
        public uint EventosPendentes {get; set;}

        public DashboardViewModel()
        {
            this.Agendamento = new List<Agendamento>();
            
        }
    }
}

RoleTopMVC/Controllers/AdministradorController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using RoleTopMVC.Enums;
using RoleTopMVC.Repositories;
using RoleTopMVC.ViewModels;

namespace RoleTopMVC.Controllers
{
    public class AdministradorController : AbstractController
    {
        AgendamentoRepository agendamentoRepository = new AgendamentoRepository();
        [HttpGet]
        public IActionResult Dashboard()
        {
            try
            {
            var tipoUsuarioSessao = uint.Parse(ObterUsuarioTipoSession());
            if(tipoUsuarioSessao.Equals((uint)TiposUsuario.ADMINISTRADOR))
            {
            var agendamento = agendamentoRepository.ObterTodos();
            DashboardViewModel dashboardViewModel = new DashboardViewModel();

            foreach (var evento in agendamento)
            {
                switch(evento.Status)
                {
                    case (uint) StatusPedidos.REPROVADO:
                    dashboardViewModel.EventosReprovados++;
                    break;
                    case (uint) StatusPedidos.APROVADO:
                        dashboardViewModel.EventosAprovados++;
                    break;
                    default:
                        dashboardViewModel.EventosPendentes++;
                        dashboardViewModel.Agendamento.Add(evento);
                    break;
                }
            }
            dashboardViewModel.NomeView = "Dashboard";
            dashboardViewModel.UsuarioEmail = ObterUsuarioSession();

            return View(dashboardViewModel); 
            }
            
            return View("Erro", new RespostaViewModel()
            {
                NomeView = "Dashboard",
                Mensagem = "Acesso restrito"
            });
            }
            catch (Exception e)
            {
                System.Console.WriteLine(e.StackTrace);
                return View("Error", new RespostaViewModel()
            {
                NomeView = "Dashboard",
                Mensagem = "Tempo Expirado"
            });
            }
        }
    }
}

RoleTopMVC/Controllers/AgendamentoController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RoleTopMVC.Enums;
using RoleTopMVC.Models;
using RoleTopMVC.Repositories;
using RoleTopMVC.ViewModels;

namespace RoleTopMVC.Controllers
{
    public class AgendamentoController : AbstractController
    {
        AgendamentoRepository agendamentoRepository = new AgendamentoRepository();
        ClienteRepository clienteRepository = new ClienteRepository();
        Agendamento agendamento = new Agendamento();
        public IActionResult Index()
        {
            var usuarioLogado = ObterUsuarioSession();

            AgendamentoViewModel avm = new AgendamentoViewModel();

            if (!string.IsNullOrEmpty(usuarioLogado))
            {
                var clienteLogado = clienteRepository.ObterPor(usuarioLogado);

                avm.UsuarioEmail = usuarioLogado;
                avm.Cliente = clienteLogado;
                
                return View(avm);
            }
            return View("Error", new RespostaViewModel(){
                Mensagem = "É necessário estar logado para realizar um agendamento, realize um cadastro caso não tenha uma conta",
                
            });
        }
        public IActionResult Registrar(IFormCollection form)

        {
            Evento evento = new Evento(){
                
                Opcional1= form["opcional1"],
                Opcional2 = form ["opcional2"],
                Endereco = form ["endereco"],
                TipoPagamento = form ["tipoPagamento"],
                TipoEvento = form ["tipoEvento"],
                Data = DateTime.Parse(form ["data"])
                };

            Cliente cliente = new Cliente()
            {
                Nome = form["nome"],
                Cpf = form["cpf"],
                Telefone = form["telefone"],
                Email = form["email"]
            };
            

            agendamento.cliente = cliente;
            agendamento.DatadoPedido = DateTime.Now;
            agendamento.evento = evento;
            
            if(agendamentoRepository.Inserir(agendamento))
            {
            return View("Sucesso", new RespostaViewModel()
            {
                Mensagem = "Aguarde a aprovação dos nossos administradores",
                NomeView = "Sucesso",
                UsuarioEmail = ObterUsuarioSession(),
                UsuarioNome = ObterUsuarioNomeSession()
            });
            }
            else
            {
            return View("Error", new RespostaViewModel()
            {
                Mensagem = "Houve um erro ao processar seu agendamento. tente novamente",
                NomeView = "Erro",
                UsuarioEmail = ObterUsuarioSession(),
                UsuarioNome = ObterUsuarioNomeSession()
            });
            }
        }
        public IActionResult Aprovar(ulong id)
    {
        Agendamento agendamento = agendamentoRepository.ObterPor(id);
        agendamento.Status = (uint) StatusPedidos.APROVADO;

        if(agendamentoRepository.Atualizar(id,agendamento))
        {
            return RedirectToAction("Dashboard", "Administrador");
        }
        else
        {
            return View("Error", new RespostaViewModel()
            {
                Mensagem = "Houve um erro ao aprovar pedido",
                NomeView = "Dashboard",
                UsuarioEmail = ObterUsuarioSession(),
                UsuarioNome = ObterUsuarioNomeSession()
            });
        }
    }
    public IActionResult Reprovar(ulong id)
    {
        Agendamento agendamento = agendamentoRepository.ObterPor(id);
        agendamento.Status = (uint) StatusPedidos.REPROVADO;

        if(agendamentoRepository.Atualizar(id, agendamento))
        {
            return RedirectToAction("Dashboard", "Administrador");
        }
        else
        {
            return View("Error", new RespostaViewModel()
            {
                Mensagem = "Houve um erro ao Reprovar pedido",
                NomeView = "Dashboard",
                UsuarioEmail = ObterUsuarioSession(),
                UsuarioNome = ObterUsuarioNomeSession()
            });
        }
    }
    }
}

RoleTopMVC/Views/Administrador/Dashboard.cshtml
@model RoleTopMVC.ViewModels.DashboardViewModel
<main>
        <h2>Dashboard</h2>
        <section id="status-pedidos">
            <h2>Status dos Agendamentos</h2>
            <div id="painel">
                <div class="box-status-pedidos aprovados">
                    <h4>Aprovados</h4>
                    <p>@Model.EventosAprovados</p>
                </div>
                <div class="box-status-pedidos pendentes">
                    <h4>Pendentes</h4>
                    <p>@Model.EventosPendentes</p>
                </div>
                <div class="box-status-pedidos reprovados">
                    <h4>Reprovados</h4>
                    <p>@Model.EventosReprovados</p>
                </div>
            </div>
        </section>

        <section id="lista-pedidos">
            <h2>Agendamentos</h2>
            <table>
                <thead>
                    <tr>
                        <th rowspan="2">Nome</th>
                        <th rowspan="2">Dia(s) do Evento</th>
                        <th rowspan="2">Tipo</th>
                        <th rowspan="2">Opcional 1</th>
                        <th rowspan="2">Opcional 2</th>
                        <th colspan="2" rowspan="2">Aprovar/Recusar</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <td colspan="7">
                            <p>Pedidos atualizados em @DateTime.Now</p>
                        </td>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach(var evento in Model.Agendamento){
                        <tr>
                            <td>@evento.cliente.Nome</td>
                            <td>@evento.evento.Data</td>
                            <td>@evento.evento.TipoEvento</td>
                            <td>@evento.evento.Opcional1</td>
                            <td>@evento.evento.Opcional2</td>
                            <td><a href='@Url.Action("Aprovar", "Agendamento", new {id = @evento.Id})'><i class="fas fa-check"></i></a></td>
                            <td><a href='@Url.Action("Reprovar", "Agendamento", new {id = @evento.Id})'><i class="fas fa-times"></i></a></td>
                        </tr>
                    }

                </tbody>
            </table>
        </section>
    </main>